stages:
  data_ingestion:
    cmd: python src/disease_classification/pipeline/data_ingestion.py
    deps:
      - src/disease_classification/pipeline/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare-base-model:
    cmd: python src/disease_classification/pipeline/prepare_base_model.py
    deps:
      - src/disease_classification/pipeline/prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/disese_classification/pipeline/model_trainer.py
    deps:
      - src/disese_classification/pipeline/model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/disease_classification/pipeline/evaluation.py
    deps:
      - src/disease_classification/pipeline/evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
